version:  '3.8'
     
services:
    database:
      container_name: database
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony_docker
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql
      
    adminer:
      image: adminer
      restart: on-failure
      ports:
        - '8080:8080'
    nginx:
       image: nginx:1.19.0-alpine
       restart: on-failure
       volumes:
         - './apps/symfonyapp/public/:/usr/src/app'
         - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
       ports:
         - '80:80'
       depends_on:
         - php

    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        volumes:
          - './apps/symfonyapp/:/usr/src/app'
        restart: on-failure
        user: 1000:1000



